apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-yi0c
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-deploy-tenant/appstudio/dc-metro-map-yi0c@sha256:1e6d0358d09dd9600d8324b2b497570943cee96d1528d528837fdf60f0858c13
        name: my-nodejs
        resources: {}
status: {}
